### ISSUE TITLE
Error while accessing localhost:8000

### ISSUE THREAD

**Issue by Vrashabh-Sontakke** [vjanz/kubernetes-demo-app#1]
I ran the app as mentioned in the readme file.
When I try to access localhost:8000 or localhost:8000/api/docs it gives error {"detail":"Not Found"} on the browser

**Comment by vjanz** [comment]
HI @Vrashabh-Sontakke , thank you for reporting.
You're right, its just `localhost:8000/docs` without `/api` prefix. Tell me if you have other problems, if not feel free to close the issue.

**Comment by Vrashabh-Sontakke** [comment]
let me create a PR to modify the docs
